name: Genomics Daily run

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  fetch-genomics-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout first repository
      uses: actions/checkout@v3
      with:
        path: github-page

    - name: Checkout second repository
      uses: actions/checkout@v3
      with:
        repository: emmecola/genomics-daily
        path: genomics-daily

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r genomics-daily/requirements.txt
        pip install -r genomics-daily/requirements_bot.txt
        pip install markdown

    - name: Run Python script and prepare summary
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        BSKY_USER: ${{ secrets.BSKY_USER }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
        MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}
      run: |
        python genomics-daily/genomics-daily.py genomics-daily/keywords.txt genomics-daily/journals.txt > github-page/genomics-daily/summary.md
        echo "" >> github-page/genomics-daily/summary.md
        echo "*Last update: $(date)*" >> github-page/genomics-daily/summary.md
        cp github-page/genomics-daily/summary.md github-page/genomics-daily/archive/summary-$(date +"%y-%m-%d").md
        python genomics-daily/genomics-daily-bot.py github-page/genomics-daily/summary.md
        python genomics-daily/rss_feeder.py --input genomics-daily/summary.md --output genomics-daily/feed.xml

    - name: Commit and push changes
      run: |
        cd github-page
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git commit -m "Update daily genomics summary"
        git push
